---
title: "Course Project: Shiny Application and Reproducible Pitch"
author: "Dr. C. Naveen Kumar"
date: "03 November, 2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---


## Cements Explore

This presentation is being created as part of the peer assessment for the coursera developing data products class. The assignment is to make sure that the students what they have learn and show how to apply it.

It have two part:

 - *_shiny_* to build data product application
 - *R-Presentation or slidify* to create data product related presentations

## Application Explore

Using the data that originally from R (*cement* dataset), which is here
(<a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html">datasets</a>) , I make a simple application of shiny so that we can understand the use of it.

The application allow user to :

- Select the data of x-axis and y-axis based on the variable of the datasets
- Select the output to be shown as Jitter or Smooth graph
- User also can choose what facet row or colum that they want.

## Code

Using the datasets cement, I do some evaluation and this is the simple code to see what data it have :

```{r}
dataset <- read.csv('cementmix.csv')
head(dataset)
```

## Link to the project and docs

1. shiny Apps : <a href="https://doccnk.shinyapps.io/DDPCourseProject/">Cement Exploration</a>
2. server.R and ui.R file : <a href="https://github.com/DrCNK/Developing-Data-Products/tree/master/CourseProject">Link</a>

Please try out different options using the application. Thank You.